version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9.29-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - custom_network
    container_name: rabbitmq
  sender:
    build:
      context: ../sender/
      dockerfile: ./docker/DockerFile
    image: patterns/cache
    networks:
      - custom_network
    hostname: application
    ports:
      - "8080:8080"
    container_name: application
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://application:8080/status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - rabbitmq
networks:
  custom_network:
    driver: bridge
